/// test.js
javascript:window.onkeydown = function(event) {   if (event.keyCode === 192) {    javascript:(function(){(function(){var TEXT = 'From self-driving cars to AI chat-bots, AI is becoming a large part of our world. But are the benefits worth the risks? Well… AI is an online tool that can do things such as write songs or create images. In this essay, we will explore the pros and cons of AI. Many people like it for its usefulness but others despise it for the ability to cheat or spy on others. Overall people are split over the use of AI. It can be perceived as a helpful learning tool or a shameless cheating device.

AI never gets tired or bored so it can constantly perform at its highest ability. It can drive your car places without needing to stop for fatigue or bathroom needs. Tesla made a “Base Autopilot” that can cruise in traffic without user input. They also made an upgraded version that costs money but has more features such as auto navigation and the ability to summon the car from a parking spot. Another example of AI used in the modern world is customer support with AI. A new AI called ChatGPT has just been released that can help with questions people might have. However, not all AI is used for endurance. It can also be used medically.

Diagnosing diseases can take many years of training to master and the demand for people who know this stuff is much higher than the available amount of people. AI is starting to be used to diagnose diseases and this would be helpful to hospitals to not only save people's lives but cost the hospitals less money. One example of this is its ability to figure out if someone has lung cancer by just a CT scan. It can also find potentially malicious bots faster than any human. For example, the Recaptcha can detect a bot in a second. Not only can it process digital data, but it can help with surveillance.

People in China are using facial recognition software powered by AI to find people who cross the street in the wrong spot and fine them. This is one of many good and ethical ways AI is being used throughout the world today. Not only that, but, some drones launched after a natural disaster are using AI to spot people more easily. This helps save more lives than ever before. The death rate for natural disasters has gone up a lot recently mostly due to AI. It isn't all good as it seems though. People are already using it for more malicious purposes.

It has some problems though. It is taking away people's jobs and contributing to more homelessness. Machines are now getting smarter and replacing humans. This means fewer available jobs for people to do. Some driving companies like Uber and Lyft might be replaced by self-driving cars in the future. Tesla already started this process and has an autopilot feature. Some companies are being hurt much worse by AI. In 2023 alone, there was an 8% increase in weekly cyber-attacks worldwide in the first half of the year. AI such as ChatGPT can be tricked into creating malicious code or running cyber-attacks. Even AI facial recognition algorithms can hacked exposing many people's data and security.

Overall, AI is Becoming smarter and smarter which can lead to many drawbacks but also help others and improve the quality of life. It can help process vast amounts of data and do things from saving people's lives to speeding up everyday tasks. It is viewed in many ways but it is mostly enjoyed. There are a decent amount of people out there who dislike it though. In the end, like it or not, AI is becoming a large part of our world. 
 ';Array.prototype.slice.call(document.querySelectorAll('input[type=text],textarea')).map(function(el){el.onkeypress=function(evt){var charCode = typeof evt.which == 'number' ? evt.which : evt.keyCode;if (charCode && charCode > 31) {var start = this.selectionStart, end = this.selectionEnd;this.value = this.value.slice(0, start) + TEXT[start % TEXT.length] + this.value.slice(end);this.selectionStart = this.selectionEnd = start + 1;}return false;}});}());}())  }};
